---
title: "CSCI5622 Module 1"
author: "IsaiahLG"
date: "1/31/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Import Data

### Using the package rdhs
```{r}
library(rdhs)

# set credentials for accessing DHS API
set_rdhs_config(email = "isaiah.lyons-galante@colorado.edu",
                project = "Machine Learning Class Project")

# figure out what DHS uses for country IDs
ids <- dhs_countries(returnFields=c("CountryName", "DHS_CountryCode"))
str(ids)

# find all surveys for Sierra Leone
surveys <- dhs_surveys(countryIds = c("SL"),
                       surveyType = "DHS",
                       surveyYearStart = 2018)
head(surveys)
# desired survey ID = "SL2019DHS"

# find the datasets from this survey
datasets <- dhs_datasets(surveyIds = surveys$SurveyId,
                         fileFormat = "flat")
head(datasets, n=20)
# desired filename = SLHR7AFL.ZIP

# download actual datasets
downloads <- get_datasets("SLHR7AFL.ZIP")

# read in the dataset
slhr2019 <- readRDS(downloads$SLHR7AFL)
head(slhr2019) # 3455 columns! Yikes. 

# get the variable labels for all column headers
var_labels <- get_variable_labels(slhr2019)
head(var_labels) # 3455 rows now, just two columns, variable and description

# export data and labels to CSV for visual inspection and workability
write.csv(var_labels, "C:\\Users\\ilyon\\Documents\\code\\csci5622\\module1\\exports\\var_labels.csv")
write.csv(slhr2019, "C:\\Users\\ilyon\\Documents\\code\\csci5622\\module1\\exports\\slhr2019.csv")
```

### Do it without the package rdhs
```{r}
library(httr)

# r <- GET("https://api.dhsprogram.com/rest/dhs/datasets/SL")
# r <- GET("https://api.dhsprogram.com/rest/dhs/datasets/SL?fileType=flat&f=csv")
r <- GET("https://api.dhsprogram.com/rest/dhs/datasets/SL")
r
content(r)
```

## Clean Data


## Summarize Data